export const Users = [
  {
    id: 1,
    profilePicture: "pic1.jpg",
    username: "Sharon",
  },
  {
    id: 2,
    profilePicture: "pic2.jpg",
    username: "James Brown",
  },
  {
    id: 3,
    profilePicture: "pic3.jpg",
    username: "John Chi",
  },
  {
    id: 4,
    profilePicture: "pic1.jpg",
    username: "Marie",
  },
  {
    id: 5,
    profilePicture: "pic1.jpg",
    username: "Rosie ",
  },
  {
    id: 6,
    profilePicture: "pic1.jpg",
    username: "Bebe Rexa",
  },
  {
    id: 7,
    profilePicture: "pic1.jpg",
    username: "Daniel ",
  },
  {
    id: 8,
    profilePicture: "pic1.jpg",
    username: "Nde",
  },
  {
    id: 9,
    profilePicture: "pic1.jpg",
    username: "My man",
  },
  {
    id: 10,
    profilePicture: "pic1.jpg",
    username: "Babyyy",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "I lovee",
    photo: "pic1.jpg",
    date: "1 day ago",
    userId: 1,
    like: 32,
    Comment: 9,
  },
  {
    id: 2,
    desc: "Love for all, Hatred for none",
    photo: "pic2.jpg",
    date: "5 mins ago",
    userId: 3,
    like: 129,
    Comment: 9,
  },
  {
    id: 3,
    desc: "Love for all, Hatred for none",
    photo: "pic3.jpg",
    date: "5 mins ago",
    userId: 2,
    like: 32,
    Comment: 9,
  },
  {
    id: 4,
    desc: "Love for all, Hatred for none",
    photo: "pic4.jpg",
    date: "5 mins ago",
    userId: 4,
    like: 32,
    Comment: 9,
  },
  {
    id: 5,
    desc: "Love for all, Hatred for none",
    photo: "pic1.jpg",
    date: "5 mins ago",
    userId: 5,
    like: 32,
    Comment: 9,
  },
  {
    id: 6,
    desc: "Love for all, Hatred for none",
    photo: "pic3.jpg",
    date: "5 mins ago",
    userId: 6,
    like: 32,
    Comment: 9,
  },
  {
    id: 7,
    desc: "Love for all, Hatred for none",
    photo: "pic2.jpg",
    date: "5 mins ago",
    userId: 7,
    like: 32,
    Comment: 9,
  },
  {
    id: 8,
    desc: "Love for all, Hatred for none",
    photo: "pic.webp",
    date: "5 mins ago",
    userId: 8,
    like: 32,
    Comment: 9,
  },
  {
    id: 9,
    desc: "Love for all, Hatred for none",
    photo: "pic4.jpg",
    date: "5 mins ago",
    userId: 9,
    like: 32,
    Comment: 9,
  },
  {
    id: 10,
    desc: "Love for all, Hatred for none",
    photo: "pic2.jpg",
    date: "5 mins ago",
    userId: 10,
    like: 32,
    Comment: 9,
  },
];
